# First-time .env setup. Never overwrites an existing server\.env unless -Force.
# Usage: .\scripts\setup-env.ps1
#        .\scripts\setup-env.ps1 -Force
#Requires -Version 5.1
[CmdletBinding()]
param(
    [switch]$Force,
    [switch]$NonInteractive
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Root = Split-Path -Parent $ScriptDir
$ServerDir = Join-Path $Root "server"
$EnvFile = Join-Path $ServerDir ".env"
$Example = Join-Path $ServerDir ".env.example"

if (-not (Test-Path $Example)) {
    Write-Error "Missing $Example"
}

if ((Test-Path $EnvFile) -and -not $Force) {
    Write-Host "==> keeping existing server\.env (not overwritten)"
    Write-Host "    reconfigure: .\scripts\setup-env.ps1 -Force"
    exit 0
}

if ((Test-Path $EnvFile) -and $Force) {
    Write-Host "==> reconfiguring server\.env (-Force)"
}
else {
    Write-Host "==> first-time setup"
}

function Read-Default([string]$Question, [string]$Default) {
    $ans = Read-Host $Question
    if ([string]::IsNullOrWhiteSpace($ans)) { return $Default }
    return $ans.Trim()
}

function Read-YesNo([string]$Question, [string]$DefaultYesNo) {
    $ans = Read-Default "$Question [$DefaultYesNo]" $DefaultYesNo
    switch -Regex ($ans.ToLowerInvariant()) {
        '^(y|yes|true|1)$' { return "true" }
        default { return "false" }
    }
}

# irm|iex still has a usable console for Read-Host — prefer asking
$interactive = -not $NonInteractive
try {
    if ([Console]::IsInputRedirected -and -not [Environment]::UserInteractive) {
        $interactive = $false
    }
}
catch { }

$serialDefault = "auto"
$portDefault = "8000"
$bedWDefault = "400"
$bedHDefault = "430"
$lanDefault = "n"  # Windows: localhost unless they opt in

if ($interactive) {
    Write-Host ""
    Write-Host "  Available on local network?"
    Write-Host "  (phones/tablets on the same Wi-Fi can open the UI)"
    $lan = Read-YesNo "  Enable" $lanDefault
    Write-Host ""
    Write-Host "  Other settings (Enter = default):"
    $serial = Read-Default "  Serial port (auto / COM3 / COM4) [$serialDefault]" $serialDefault
    $port = Read-Default "  HTTP port [$portDefault]" $portDefault
    $bedW = Read-Default "  Bed width mm [$bedWDefault]" $bedWDefault
    $bedH = Read-Default "  Bed height mm [$bedHDefault]" $bedHDefault
}
else {
    Write-Host "    non-interactive — defaults (LAN off). Edit server\.env anytime."
    $serial = $serialDefault
    $lan = "false"
    $port = $portDefault
    $bedW = $bedWDefault
    $bedH = $bedHDefault
}

@(
    "# Generated by scripts/setup-env.ps1 — safe to edit. Updates never overwrite this file."
    "SERIAL_PORT=$serial"
    "SERIAL_BAUD=115200"
    "BED_WIDTH_MM=$bedW"
    "BED_HEIGHT_MM=$bedH"
    "LAN_ACCESS=$lan"
    "PORT=$port"
) | Set-Content -Path $EnvFile -Encoding utf8

Write-Host ""
Write-Host "    wrote $EnvFile"
if ($lan -eq "true") {
    Write-Host "    local network: ON  →  http://<this-pc>:$port"
}
else {
    Write-Host "    local network: OFF →  http://127.0.0.1:$port only"
}
Write-Host "      SERIAL_PORT=$serial  bed=${bedW}x${bedH}"
