#!/usr/bin/env bash
# First-time .env setup. Never overwrites an existing server/.env unless FORCE=1.
# Usage: ./scripts/setup-env.sh
#        FORCE=1 ./scripts/setup-env.sh   # re-run wizard
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SERVER_DIR="$ROOT/server"
ENV_FILE="$SERVER_DIR/.env"
EXAMPLE="$SERVER_DIR/.env.example"

prompt() {
  local q="$1" def="$2" ans=""
  if [[ -r /dev/tty ]]; then
    printf "%s [%s]: " "$q" "$def" >/dev/tty
    IFS= read -r ans </dev/tty || true
  elif [[ -t 0 ]]; then
    printf "%s [%s]: " "$q" "$def"
    IFS= read -r ans || true
  fi
  if [[ -z "${ans// }" ]]; then
    printf '%s' "$def"
  else
    printf '%s' "$ans"
  fi
}

yes_no() {
  local q="$1" def="$2" ans
  ans="$(prompt "$q (y/n)" "$def")"
  case "${ans,,}" in
    y|yes|true|1) printf 'true' ;;
    *) printf 'false' ;;
  esac
}

if [[ ! -f "$EXAMPLE" ]]; then
  echo "error: missing $EXAMPLE" >&2
  exit 1
fi

if [[ -f "$ENV_FILE" && "${FORCE:-0}" != "1" ]]; then
  echo "==> keeping existing server/.env (not overwritten)"
  echo "    reconfigure: FORCE=1 $0"
  exit 0
fi

if [[ -f "$ENV_FILE" && "${FORCE:-0}" == "1" ]]; then
  echo "==> reconfiguring server/.env (FORCE=1)"
else
  echo "==> first-time setup"
fi

SERIAL_DEFAULT="auto"
PORT_DEFAULT="8000"
BED_W_DEFAULT="400"
BED_H_DEFAULT="430"
# Pi / Linux: LAN on is usually what you want
LAN_DEFAULT_YN="y"

INTERACTIVE=0
if [[ -r /dev/tty ]] || [[ -t 0 ]]; then
  INTERACTIVE=1
fi

if [[ "$INTERACTIVE" == "1" && "${NONINTERACTIVE:-0}" != "1" ]]; then
  echo ""
  echo "  Available on local network?"
  echo "  (phones/tablets on the same Wi-Fi can open the UI)"
  LAN_ACCESS="$(yes_no "  Enable" "$LAN_DEFAULT_YN")"
  echo ""
  echo "  Other settings (Enter = default):"
  SERIAL_PORT="$(prompt "  Serial port (auto / /dev/ttyUSB0 / /dev/ttyACM0)" "$SERIAL_DEFAULT")"
  PORT="$(prompt "  HTTP port" "$PORT_DEFAULT")"
  BED_WIDTH_MM="$(prompt "  Bed width mm" "$BED_W_DEFAULT")"
  BED_HEIGHT_MM="$(prompt "  Bed height mm" "$BED_H_DEFAULT")"
else
  echo "    non-interactive — defaults (LAN on). Edit server/.env anytime."
  SERIAL_PORT="$SERIAL_DEFAULT"
  LAN_ACCESS="true"
  PORT="$PORT_DEFAULT"
  BED_WIDTH_MM="$BED_W_DEFAULT"
  BED_HEIGHT_MM="$BED_H_DEFAULT"
fi

cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh — safe to edit. Updates never overwrite this file.
SERIAL_PORT=$SERIAL_PORT
SERIAL_BAUD=115200
BED_WIDTH_MM=$BED_WIDTH_MM
BED_HEIGHT_MM=$BED_HEIGHT_MM
LAN_ACCESS=$LAN_ACCESS
PORT=$PORT
EOF

echo ""
echo "    wrote $ENV_FILE"
if [[ "$LAN_ACCESS" == "true" ]]; then
  echo "    local network: ON  →  http://<this-host>:$PORT"
else
  echo "    local network: OFF →  http://127.0.0.1:$PORT only"
fi
echo "      SERIAL_PORT=$SERIAL_PORT  bed=${BED_WIDTH_MM}x${BED_HEIGHT_MM}"
